import { ROLES, type Role } from "../constants/roles";
import { 
  LayoutDashboard, 
  Users, 
  Settings, 
  FileText, 
  Files, 
  ShieldCheck, 
  ClipboardCheck, 
  Briefcase, 
  Calendar, 
  GraduationCap, 
  Mail, 
  Bot, 
  CreditCard, 
  Shield, 
  BarChart3, 
  Ticket, 
  HelpCircle,
  Package,
  FileSearch,
  CheckSquare,
  type LucideIcon 
} from "lucide-react";

export const DASHBOARD_NAVIGATION: Record<Role, { label: string; href: string; icon: LucideIcon }[]> = {
  [ROLES.CLIENT]: [
    { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
    { label: "My Membership", href: "/dashboard/membership", icon: ShieldCheck },
    { label: "My Saved Files", href: "/my-saved-files", icon: Files },
    { label: "Document Library", href: "/dashboard/library", icon: FileText },
    { label: "My Forms / Checklist", href: "/dashboard/forms", icon: ClipboardCheck },
    { label: "RAMS Builder", href: "/rams-builder", icon: Briefcase },
    { label: "Checklist Completion", href: "/dashboard/checklist", icon: CheckSquare },
    { label: "Risk Assessment Completion", href: "/dashboard/risk-assessment", icon: Shield },
    { label: "Question Set Details", href: "/dashboard/questions", icon: FileSearch },
    { label: "Book Site Visit", href: "/dashboard/book-visit", icon: Calendar },
    { label: "Training", href: "/dashboard/training", icon: GraduationCap },
    { label: "Newsletters", href: "/dashboard/newsletters", icon: Mail },
    { label: "Virtual Agent", href: "/virtual-agent", icon: Bot },
    { label: "Buy Extras", href: "/dashboard/extras", icon: Package },
    { label: "Manage Subscription", href: "/dashboard/subscription", icon: CreditCard },
    { label: "How-to Guides / Support", href: "/dashboard/support", icon: HelpCircle },
    { label: "Account Settings", href: "/dashboard/settings", icon: Settings },
  ],
  [ROLES.ADMIN]: [
    { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
    { label: "User Management", href: "/dashboard/users", icon: Users },
    { label: "Membership & Subscriptions", href: "/dashboard/admin/subscriptions", icon: ShieldCheck },
    { label: "Document Library", href: "/dashboard/admin/library", icon: FileText },
    { label: "My Saved Files", href: "/my-saved-files", icon: Files },
    { label: "RAMS Content", href: "/rams-builder", icon: Briefcase },
    { label: "Booking Management", href: "/dashboard/admin/bookings", icon: Calendar },
    { label: "Add-ons Management", href: "/dashboard/admin/add-ons", icon: Package },
    { label: "Payment / Stripe", href: "/dashboard/admin/payments", icon: CreditCard },
    { label: "Content Management", href: "/dashboard/admin/content", icon: FileText },
    { label: "Newsletters", href: "/dashboard/admin/newsletters", icon: Mail },
    { label: "Virtual Agent", href: "/virtual-agent", icon: Bot },
    { label: "Training Management", href: "/dashboard/admin/training", icon: GraduationCap },
    { label: "Support Tickets", href: "/dashboard/admin/tickets", icon: Ticket },
    { label: "How-to Guides", href: "/dashboard/admin/guides", icon: HelpCircle },
    { label: "Reports & Analytics", href: "/dashboard/admin/analytics", icon: BarChart3 },
    { label: "Security / GDPR", href: "/dashboard/admin/security", icon: Shield },
    { label: "Email Templates", href: "/dashboard/admin/email-templates", icon: Mail },
    { label: "System Settings", href: "/dashboard/admin/settings", icon: Settings },
  ],
};
